### ISSUE TITLE
Getting lost in the configuration file.

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#10]
I fell time has arrived to shorten the configuration file, as of now, the feeds links, the portfolio and chart's setting are being served from a single file, it would be nice if the Portfolio, charts and rss/feeds entry values are being assigned to respective files rather then the main configuration file, and the path to those files can be included in the main configuration, because with the each update it becomes difficult to figure out the exact locations of the each configuration setting.

**Comment by taoteh1221** [comment]
Sorry you're getting a bit lost in the config file. This is partially due to reorganizing it over the last few releases. That work is done now, and it should be easier from here onward to find the settings you need with everything properly categorized now.

I had thought about seperating the config into multiple files, but after thinking it over I decided that over-complicates things for new / inexperienced users on configuration usage.

**Comment by s1-ranjan** [comment]
As of now I found three unwanted/ user-specific sections:
i: Chart and Price Alert
ii: Standard Rss
iii: Portfolio Asserts
Above mentioned sections should be handled from respective files rather than from the main configuration file, this will definitely shorten the main configuration file, moreover in the above list point's i and iii are more user specific in which people will try to define their currencies for the chart along with the including once coin in the list for market observation.
The main problem comes with the update, with each update there are some modification in the main configuration file, which causes some trouble, to edit the whole configuration file so that to list and modify the chart and Portfolio section, with the split in the configuration file there is a less likelihood of attaining those two section as this two section will remain constant unchanged, I hope I am able to convey my thoughts on this.

**Comment by taoteh1221** [comment]
As I said earlier, part of the reason for the confusion was the constant refining of those categories (re-categorizing the content and renaming for a better UX). I honestly would love to split the config file up like you said, but the problem arises when new users have multiple config files instead of one config file. It's just not feasible to do. 

I'm sorry about re-categorizing the config file on you alot the past few releases, that work is now done. In fact, I will feature-freeze the config structuring, so the structure stays the same from here forward (other than removing stale markets and adding interesting new ones on ocassion to the demo configuration). There are trade offs for everything thing tweaked inside an app, and unfortunately this is as balanced as it can get without over-complocating things.

**Comment by s1-ranjan** [comment]
I don't find any issues with this split, we are only required to choose the names and the locations of the files wisely such as
i: Chart and Price Alert can be accommodated in  chart.php 
ii: Standard Rss can be accommodated in rss.php
iii: Portfolio Asserts can be accommodated in asserts.php
Above files (chart.php, rss.php, asserts.php)can be placed in the php folder under  app-lib or some other location, without creating multiple config file, and this solution can be a good way to shorten the config file, and moreover it'll not cause any trouble to the new user as this'll not create multiple config file, rather than a single config file with three different branches and a single configure file.
Confusion can arise only if we use terms like chart-config.php or something like that, so if we go with a neat names as I have suggest this'll not cause any issue to the new user.

**Comment by taoteh1221** [comment]
I'm very sorry Ranjan, I don't agree it's a good idea to split the config file up into multiple config files (I already thought it over in depth a long time ago). In future releases, you won't have to edit config.php at all...config will be run from a cached version of your customized config that will never change between updates. At this point, config.php will only be used as a 'default' config for new installs, and 'reset' to default (like resetting your phone). I do promise that I won't reorganize the config categorization again though. That will now remain the same going forward.
