### ISSUE TITLE
Support for INR in trading pairs and Supporting exchanges

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#2]
Please add INR in the supported feat Currency list and extend the list for following exchanges which supports INR.
1. localbitcoins
2. zebpay :- https://build.zebpay.com/Home/Documentation
3. buyucoin:- https://www.buyucoin.com/api_info
4. bitbns:- https://bitbns.com/order/getTickerWithVolume/

**Comment by taoteh1221** [comment]
Thanks for your feedback. I've coded in INR [localbitcoins] support for the upcoming v4.07.3 release (will be released before the end of January). https://github.com/taoteh1221/DFD_Cryptocoin_Values/commit/3519354f2d8e9c36b9243edbf264d0e9ea8b3710

I will look into adding those additional exchanges for further INR support as well.

**Comment by taoteh1221** [comment]
@s1-ranjan v4.07.3 has just been released, and it includes INR localbitcoins support. I plan to add your desired exchanges in the upcoming v4.08.0 release. I'll let you know when it's out. Thanks again for your feedback, I appreciate it.

**Comment by s1-ranjan** [comment]
@taoteh1221 I tried to use it on my server but I am receiving this error message "The page isn’t redirecting properly" on  Apache Version: 2.4  and  Version Nginx: 1.6

**Comment by taoteh1221** [comment]
Hello @s1-ranjan thanks for your feedback. Please try the v4.07.4 release I just released a minute ago, and see if your error message goes away? Let me know if it still happens, and I'll figure out what's wrong.  I patched various bugs here and there in this release, AND I also added your upgrade alert feature request. https://github.com/taoteh1221/DFD_Cryptocoin_Values/releases

**Comment by s1-ranjan** [comment]
Hi @taoteh1221 , I find the .htaccess file is causing issue in my server if I use with following entry
RewriteEngine On
RewriteCond %{SERVER_PORT} !=443
RewriteRule ^ https://github.com%{REQUEST_URI} [NS,R,L]
 it work's but the script is rewriting the .htaccess which is causing me the issue

**Comment by taoteh1221** [comment]
@s1-ranjan I wonder if the new required HTTPS connection feature is the issue of your error, because your load balancer MAY not be letting the app detect if you are connected to the current server instance via HTTPS. Anyways, we'll figure it out. Just holler if v4.07.4 or greater continue giving you trouble, and I'll patch it up better to run with a load balancer.

**Comment by taoteh1221** [comment]
@s1-ranjan I believe I have this redirect issue fixed, and I will be releasing it in v4.07.5 (sometime tomorrow) https://github.com/taoteh1221/DFD_Cryptocoin_Values/commit/9ff4d243180cf13859465d47f61363d8c77ea9ae  Meanwhile, if you change the files: 
/templates/back-end/root-app-directory-htaccess.template 
and 
./htaccess (in the main app directory) to this code below, it should fix your issue:
```

<IfModule mod_rewrite.c>

RewriteEngine on


  <IfModule mod_ssl.c>
  
  RewriteCond %{HTTPS} off
  
  RewriteCond %{HTTP:X-Forwarded-Proto} !https
  
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
  
  </IfModule>


</IfModule>

```

**Comment by s1-ranjan** [comment]
Thanks it seems to be working, I am wondering with one question. With every update I am loosing the chats of my previous data's so is there any solution to overcome this problem, so that charts can be survive the upgrade process

**Comment by taoteh1221** [comment]
Great, thanks for letting me know...glad it worked. The charts should not be affected by upgrades, UNLESS you upgrade from a version earlier than 4.04.x. What version did you upgrade from? I'll look into this, it should not be happening. Thanks for mentioning this.

**Comment by taoteh1221** [comment]
@s1 I was wrong, it's actually after v4.02.x you loose all your previous chart data (major charts overhaul that isn't backwards compatible starting in v4.03.0). Did you upgrade from v4.02.x or earlier version when you had your charts data reset? Or was it an issue upgrading from a higher version?

**Comment by s1-ranjan** [comment]
@taoteh1221 , I performed upgrade from v3.50.0 and all my chats have gone, so I was thinking it would be better to store the data in the database rather than to store in the folder and the structures of the data tables can be altered in the future if required in the future, if you find some better solution then please let me know.

**Comment by taoteh1221** [comment]
@s1-ranjan My apologies you lost all your charts from v3.50.0. I did a major overhaul which included all chart trade 24 hour volume be set to the volume of the paired asset (rather than the volume of the primary asset), so the charts from program versions earlier than v4.03.0 were not backwards compatible. It would no have mattered if I stored in a database or in files...it would not have been backwards compatible either way. Charts should always be compatible going forward from v4.03.0 though, because I've completed revising the chart logic.

The primary reason I don't use an SQL database is so low power devices (like Raspberry Pi computers) with low memory usage requirements can still easily run this app. This allows people without websites to install the app and run it 27 hours a day affordably on their home network (I even have an auto-install script included for Raspberry Pis).

**Comment by s1-ranjan** [comment]
@taoteh1221 , I was thinking about sqlite as it claims to be lightweight but powerful database with using no resource from the server can be a good choice, what do you think about such implementation?

**Comment by taoteh1221** [comment]
Thanks for pointing out SQLite, that would be great to use for data that requires query capability (user accounts etc). That said, chart data doesn't need query capability, and it would bloat an SQL database backup (rather than just zip archive a charts folder, which I already have now for chart backups in this app)...and the upcoming lite charts (to increase page load time with charts enabled) really work well as flat files.

I have added your requested exchanges and all requested features, just have to spend a few hours tidying up some other coding, then I will release a new version later today (I will let you know). I'm adding in better support for NGINX, so please let me know if something does not work on your setup, and I'll patch it for you. Thanks very much for all your feedback, I really appreciate it a lot. :smile:

**Comment by s1-ranjan** [comment]
Thanks for implementing and improving this product every things works for me,
Well I was thinking why not to make the availability of the chat be controlled from the setting page, I think this can help others with some more degree of freedom and fell of flexibility.
It'll be great to if INR can be accommodated in the chat page too.
Can this application use bootstrap so that this page can be accessed from any device.

**Comment by taoteh1221** [comment]
@s1-ranjan Your welcome, glad to here everything is working fine for you with the latest release. You already can add any market to the charts in config.php. See the example I just added a minute ago on github in config.php, also see the notes in this config section on how to add your own: https://github.com/taoteh1221/DFD_Cryptocoin_Values/blob/master/config.php#L348

Adding charts in the config.php file in the above manner adds the chart as an option in the "Activate Charts" modal (button at the top left of the charts page).

This application already uses bootstrap, and can be viewed on any sized screen / device. That said, since we are dealing with a table layout for the portfolio, it is not easily possible to have large text within the table data without ruining the feel of seeing all the portfolio data at the same time.

**Comment by taoteh1221** [comment]
@s1-ranjan In case you did not notice, you can make all charts show their INR value, by setting:
```
$app_config['btc_primary_currency_pairing'] = 'inr'; 

$app_config['btc_primary_exchange'] = 'bitbns';

```
https://github.com/taoteh1221/DFD_Cryptocoin_Values/blob/master/config.php#L163

Then instead of having USD charts, you will have INR charts. :+1:

**Comment by s1-ranjan** [comment]
Michael I found your fist solution is giving me a better result where as the second solution is not giving good result although the second solution seems to be very simple as I required to edit only two different lines of configuration file well that will require some work in order to fit well but this can cause issues in the long run as there can be issues with (may be) non supported coins at some exchange, hence your first suggestion is good and it can be applied.

**Comment by s1-ranjan** [comment]
> Adding charts in the config.php file in the above manner adds the chart as an option in the "Activate Charts" modal (button at the top left of the charts page).

I agree with you but if a function is added to the settings which writes the availability feature in the cokey then this can be of use to the returning visitors who don't want to see the loading of the chart, as this process is a bit slow and it slows the process of page loading.

**Comment by taoteh1221** [comment]
@s1-ranjan They are not separate solutions, you should do both of them.

The first solution just adds the bitbns IRN / BTC market as a chart (or if you change the last parameter in that setting to "both", it will do price alerts too for bitbns INR/BTC).

The second solution shows INR charts #EQUIVALENT# VALUE FOR #ALL MARKETS# (INR DOES #NOT# NEED TO BE SUPPORTED BY THAT EXCHANGE, it just shows the INR value of that market, whether it is EUR USD / whatever).

 You can still see USD / EUR / whatever market charts without converting to INR, even after doing solution 2. See the "Activate Charts" options top left of the charts page, YOU NOW HAVE INR CHARTS FOR EVERY MARKET, #BUT YOU STILL HAVE EUR / USD / WHATEVER# CHARTS TOO.

**Comment by taoteh1221** [comment]
Also, you don't need to have charts enabled, and the "activate charts" are only shown to you as your personal settings, NOT to everybody who views the app (EVERYTHING in the interface is per user personal / private settings, nobody else can see it). If you don't want a chart to show for yourself, just don't activate it (no charts show by default, you need to activate each one in your charts page PERSONAL settings).

**Comment by taoteh1221** [comment]
@s1-ranjan I will add the word "Equivalent" next to the Calculated Equivalent charts in the next release. That should clear up some of the confusion. So that BTC / USD (INR) chart will then read BTC / USD (INR Equivalent Value)

**Comment by taoteh1221** [comment]
@s1-ranjan What is happening is the application is automatically calculating what the equivalent value is in your primary currency. You will see you also still have the normal charts as well. You can turn on / off any chart you want. This is useful if for instance you want to buy Litecoin, but you would like to see what the value in INR looks like, so you get a better feel for the value.

**Comment by taoteh1221** [comment]
@s1-ranjan Or the coin has no INR market, it still allows you to see the coin values in INR. :+1:

**Comment by taoteh1221** [comment]
Rai, you were right, there were a few bugs with the charts and it could be clarified more. I have patched the issues, and they will be fixed in the next release. I will let you know when v4.07.7 is released with the fixes. Here are some screenshots of the fixes...
![Screenshot from 2020-02-03 21-55-57](https://user-images.githubusercontent.com/1760489/73710010-b9a59580-46d0-11ea-8e0b-c6f6eadf3fdb.png)
![screencapture-raspi-dragonfrugal-network-index-php-2020-02-03-21_53_55](https://user-images.githubusercontent.com/1760489/73710016-bf9b7680-46d0-11ea-84d2-80ffee737b8a.png)

**Comment by taoteh1221** [comment]
@s1-ranjan  v4.07.7 will be released tomorrow with fixes for the charts. I added an INR / localbitcoins chart/alert configuration, since localbitcoins Bitcoin prices seem WAY MORE NORMAL than the HIGH PRICE paid for coins at Bitbns ($13,000 per bitcoin, compared to $9,000 per bitcoin at localbitcoins, BIG DIFFERENCE). I also created a power user configuration to set the preferred INR currency market to localbicoins for global INR support throughout the app. This should give you a better user experience.

I'm going to close this issue ticket, since it looks like you should be all set now. Thank you VERY MUCH for all your user feedback, it helps me make this portfolio tracker a better user experience. Please don't hsitate to open a new issue if you have any new problems or requests, and I'll help you figure things out. Cheers for now. :smile:

**Comment by taoteh1221** [comment]
v4.07.7 is out, with a better experience using charts (and many bug fixes): https://github.com/taoteh1221/DFD_Cryptocoin_Values/releases

I had a horrible time testing using bitbns as the default market, I highly suggest this setup below for INR in the config file...it worked great for me, it will send your price alerts in INR, and give you an OPTIONAL chart for INR value for non-INR markets (IF THE MARKET IS NOT AN INR MARKET):

```

$app_config['btc_primary_currency_pairing'] = 'inr';

$app_config['btc_primary_exchange'] = 'localbitcoins';

$app_config['primary_currency_decimals_max'] = 3;

```
